gzip on;
gzip_types text/plain text/css application/javascript application/json image/svg+xml;
gzip_min_length 1024;

server {
    listen 80;
    server_name xpl0day.com www.xpl0day.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name xpl0day.com www.xpl0day.com;

    ssl_certificate /etc/letsencrypt/live/xpl0day.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xpl0day.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    root /usr/share/nginx/html;
    index index_HTB.html;

    location / {
        try_files $uri $uri/ /index_HTB.html;
    }
}
